input {
  tcp {
    port => 5000
    codec => json
  }
  udp {
    port => 5000
    codec => json
  }
  beats {
    port => 5044
  }
  file {
    path => "/usr/share/logstash/external-logs/backend.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    type => "backend-log-file"
    codec => "plain"
  }
}

filter {
  if [type] == "syslog" {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" }
    }
  }
  if [type] == "backend-log-file" {
    mutate {
      rename => { "host" => "log_host" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["https://elasticsearch:9200"]
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
    index => "logstash-%{+YYYY.MM.dd}"
    ssl_enabled => true
    ssl_certificate_authorities => "/usr/share/logstash/config/elasticsearch-certs/ca.crt"
    ssl_verification_mode => "none"
  }
  
  stdout {
    codec => rubydebug
  }
}
