# Generated by Django 5.2.12 on 2026-03-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='seats',
        ),
    ]
