# ModSecurity rule includes
Include /etc/nginx/modsecurity.d/modsecurity.conf
Include /etc/nginx/modsecurity.d/crs-setup.conf
Include /etc/nginx/modsecurity.d/custom-rules.conf
Include /etc/modsecurity.d/owasp-crs/rules/*.conf
