# Generated by Django 6.0.3 on 2026-03-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_trip_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('STARTED', 'Started'), ('ENDED', 'Ended')], default='CREATED', max_length=20),
        ),
    ]
