# Generated by Django 5.2.12 on 2026-03-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_default_bus_driver_default_route'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='default_route',
        ),
        migrations.AddField(
            model_name='driver',
            name='default_routes',
            field=models.ManyToManyField(blank=True, to='routes.route'),
        ),
    ]
